/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ConexionBD;
import controlador.Controlador_MantenimientoUsuarios;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Usuario
 */
public class FRM_MantenimientoUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoUsuarios
     */
    
    Controlador_MantenimientoUsuarios controlador_MantenimientoUsuarios;
    
    public FRM_MantenimientoUsuarios(ConexionBD conexion) {
        initComponents();
        setVisible(false);
        setResizable(false);
        setLocationRelativeTo(null);
        estadoInicial();
        controlador_MantenimientoUsuarios=new Controlador_MantenimientoUsuarios(this,conexion);
        jbConsultar.addActionListener(controlador_MantenimientoUsuarios);
        jbAgregar.addActionListener(controlador_MantenimientoUsuarios);
        jbModificar.addActionListener(controlador_MantenimientoUsuarios);
        jbEliminar.addActionListener(controlador_MantenimientoUsuarios);
    }
    public void estadoInicial()
    {
        jtIDUsuario.setEnabled(true);
        jtNombreUsuario.setEnabled(false);
        jpfContraseniaUsuario.setEnabled(false);
        jtIDUsuario.setText("");
        jtNombreUsuario.setText("");
        jpfContraseniaUsuario.setText("");
        jcbModificarContrasenia.setEnabled(false);
        jcbModificarContrasenia.setSelected(false); 
        jbConsultar.setEnabled(true);
        jbAgregar.setEnabled(false);
        jbModificar.setEnabled(false);
        jbEliminar.setEnabled(false);
    }
    public int devolverIDUsuario()
    {
        return Integer.parseInt(jtIDUsuario.getText());
    }
    public Usuario devolverInformacion()
    {
        Usuario usuario;        
        if(jcbModificarContrasenia.isSelected())
        {
            usuario=new Usuario(Integer.parseInt(jtIDUsuario.getText()),jtNombreUsuario.getText(),jpfContraseniaUsuario.getText());       
        }
        else
        {
            usuario=new Usuario(Integer.parseInt(jtIDUsuario.getText()),jtNombreUsuario.getText(),"");
        }        
        return usuario;
    }
    public void mostrarInformacion(Usuario usuario)
    {
        jtNombreUsuario.setText(usuario.getNombreUsuario());
        jpfContraseniaUsuario.setText(usuario.getContraseniaUsuario()); 
    }
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }
    public void habilitarOpcionesModificarEliminar()
    {
        jtIDUsuario.setEnabled(false);
        jtNombreUsuario.setEnabled(true);
        jpfContraseniaUsuario.setEnabled(false);
        jcbModificarContrasenia.setEnabled(true);
        //
        jbConsultar.setEnabled(false);
        jbAgregar.setEnabled(false);
        jbModificar.setEnabled(true);
        jbEliminar.setEnabled(true);
    }
    public void habilitarOpcionAgregar()
    {
        jtIDUsuario.setEnabled(false);
        jtNombreUsuario.setEnabled(true);
        jpfContraseniaUsuario.setEnabled(true);
        jcbModificarContrasenia.setEnabled(false);
        jcbModificarContrasenia.setSelected(true); 
        jbConsultar.setEnabled(false);
        jbAgregar.setEnabled(true);
        jbModificar.setEnabled(false);
        jbEliminar.setEnabled(false);
    }
    public boolean consultarAlUsuario(String mensaje)
    {
        if( (JOptionPane.showConfirmDialog(null,mensaje,"Confirmar",JOptionPane.YES_NO_OPTION))==0)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlIDUsuario = new javax.swing.JLabel();
        jlNombreUsuario = new javax.swing.JLabel();
        jlContraseniaUsuario = new javax.swing.JLabel();
        jtIDUsuario = new javax.swing.JTextField();
        jtNombreUsuario = new javax.swing.JTextField();
        jpfContraseniaUsuario = new javax.swing.JPasswordField();
        jbConsultar = new javax.swing.JButton();
        jbAgregar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jcbModificarContrasenia = new javax.swing.JCheckBox();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("MantenimientoUsuarios");

        jlIDUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlIDUsuario.setText("ID Usuario:");

        jlNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlNombreUsuario.setText("Nombre Usuario:");

        jlContraseniaUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlContraseniaUsuario.setText("Contraseña Usuario:");

        jtIDUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jtNombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jpfContraseniaUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jbConsultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/buscar.png"))); // NOI18N
        jbConsultar.setText("Consultar");

        jbAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/agregar.png"))); // NOI18N
        jbAgregar.setText("Agregar");

        jbModificar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/modificar.png"))); // NOI18N
        jbModificar.setText("Modificar");

        jbEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jbEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/eliminar.png"))); // NOI18N
        jbEliminar.setText("Eliminar");

        jcbModificarContrasenia.setText("Modificar Contraseña");
        jcbModificarContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbModificarContraseniaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlIDUsuario)
                            .addComponent(jlNombreUsuario)
                            .addComponent(jlContraseniaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jpfContraseniaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbModificarContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(jbModificar)
                                .addGap(18, 18, 18)
                                .addComponent(jbEliminar))
                            .addComponent(jtIDUsuario)
                            .addComponent(jtNombreUsuario))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIDUsuario)
                    .addComponent(jtIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreUsuario)
                    .addComponent(jtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlContraseniaUsuario)
                    .addComponent(jpfContraseniaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbModificarContrasenia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbConsultar)
                    .addComponent(jbAgregar)
                    .addComponent(jbModificar)
                    .addComponent(jbEliminar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbModificarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbModificarContraseniaActionPerformed
        if(jcbModificarContrasenia.isSelected())
        {
            jpfContraseniaUsuario.setEnabled(true);
            jpfContraseniaUsuario.setText("");
        }
        else
        {
            jpfContraseniaUsuario.setEnabled(false);
            jpfContraseniaUsuario.setText("Seguridad2025.");
        }
    }//GEN-LAST:event_jcbModificarContraseniaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbConsultar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JCheckBox jcbModificarContrasenia;
    private javax.swing.JLabel jlContraseniaUsuario;
    private javax.swing.JLabel jlIDUsuario;
    private javax.swing.JLabel jlNombreUsuario;
    private javax.swing.JPasswordField jpfContraseniaUsuario;
    private javax.swing.JTextField jtIDUsuario;
    private javax.swing.JTextField jtNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
