/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ConexionBD;
import controlador.Controlador_MenuPrincipal;
import controlador.MD5;

/**
 *
 * @author Usuario
 */
public class FRM_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MenuPrincipal
     */
    
    private Controlador_MenuPrincipal controlador_MenuPrincipal;
    
    public FRM_MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        controlador_MenuPrincipal=new Controlador_MenuPrincipal();
        jmi_Salir.addActionListener(controlador_MenuPrincipal);
        jmi_RegistroUsuarios.addActionListener(controlador_MenuPrincipal);
        jmi_Login.addActionListener(controlador_MenuPrincipal);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmb_BarraMenu = new javax.swing.JMenuBar();
        jm_Home = new javax.swing.JMenu();
        jmi_Login = new javax.swing.JMenuItem();
        jmi_Salir = new javax.swing.JMenuItem();
        jm_Registro = new javax.swing.JMenu();
        jmi_RegistroUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_Home.setText("Home");

        jmi_Login.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_Login.setText("Login");
        jm_Home.add(jmi_Login);

        jmi_Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_Salir.setText("Salir");
        jm_Home.add(jmi_Salir);

        jmb_BarraMenu.add(jm_Home);

        jm_Registro.setText("Registro");

        jmi_RegistroUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmi_RegistroUsuarios.setText("Usuarios");
        jmi_RegistroUsuarios.setActionCommand("RegistroUsuarios");
        jm_Registro.add(jmi_RegistroUsuarios);

        jmb_BarraMenu.add(jm_Registro);

        setJMenuBar(jmb_BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jm_Home;
    private javax.swing.JMenu jm_Registro;
    private javax.swing.JMenuBar jmb_BarraMenu;
    private javax.swing.JMenuItem jmi_Login;
    private javax.swing.JMenuItem jmi_RegistroUsuarios;
    private javax.swing.JMenuItem jmi_Salir;
    // End of variables declaration//GEN-END:variables
}
