/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ConexionBD;
import controlador.Controlador_Login;

import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author Usuario
 */
public class FRM_Login extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Login
     */
    
    Controlador_Login controlador_Login;
    
    public FRM_Login(ConexionBD conexion,FRM_MenuPrincipal frm_MenuPrincipal) {
        initComponents();
        setVisible(false);
        setResizable(false);
        setLocationRelativeTo(null);
        
        controlador_Login=new Controlador_Login(this,conexion,frm_MenuPrincipal);
        jb_Login.addActionListener(controlador_Login);
    }
    public Usuario getDatosLogin()
    {
        return new Usuario(Integer.parseInt(jt_IDUsuario.getText()),"",jpf_Contrasenia.getText());
    }
    public void mostrarMensaje(String mensaje)
    {
        JOptionPane.showMessageDialog(null,mensaje);
    }
    public void estadoInicial()
    {
        jt_IDUsuario.setText("");
        jpf_Contrasenia.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_Login = new javax.swing.JButton();
        jl_Usuario = new javax.swing.JLabel();
        jl_Contrasenia = new javax.swing.JLabel();
        jt_IDUsuario = new javax.swing.JTextField();
        jpf_Contrasenia = new javax.swing.JPasswordField();

        jb_Login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jb_Login.setText("Login");

        jl_Usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_Usuario.setText("ID Usuario:");

        jl_Contrasenia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_Contrasenia.setText("Contraseña:");

        jt_IDUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jt_IDUsuario.setText("101110111");

        jpf_Contrasenia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jpf_Contrasenia.setText("Seguridad2025.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jb_Login)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jl_Contrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                    .addComponent(jl_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt_IDUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpf_Contrasenia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Usuario)
                    .addComponent(jt_IDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Contrasenia)
                    .addComponent(jpf_Contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_Login)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_Login;
    private javax.swing.JLabel jl_Contrasenia;
    private javax.swing.JLabel jl_Usuario;
    private javax.swing.JPasswordField jpf_Contrasenia;
    private javax.swing.JTextField jt_IDUsuario;
    // End of variables declaration//GEN-END:variables
}
